apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: default
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: postgres:9.5
          imagePullPolicy: IfNotPresent
          command: [ 'psql' ]
          args: [ '-c', 'SELECT current_database();' ]
          env:
            - name: PGDATABASE
              value: postgres
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: db-conn
                  key: endpoint
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: db-conn
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-conn
                  key: password
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: db-conn
                  key: port